//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Forma.java
//  @ Date : 10/03/2012
//  @ Author : 
//
//




public class Forma {
	public double regla;
	public double longitud;
	public double max() {
	
	}
}
